Update ununifid-installation-and-setup.md
UnUniFi/gitbook pull request #14
Opened 2022-06-27 16:12 UTC by glukosseth

# Description

### Corresponding Issue
**Issue number** - 3

## Entry to the community program
**Discord-userId** - `Aleksei#7906`   
**UnUniFi-walletAddress** - `ununifi1ydtts8a9r5jr0qmls9cy60p2j9ewvg6mrnkh4z`

### Author Checklist
- [v] Checked Contribute guide line document
- [v] provided a link to the relevant issue or specification
- [v] reviewed "Files changed" and left comments if necessary
- [v] entered the necessary information for the community program

### Reviewers Checklist
- [ ] confirmed the content is effective

2022-07-01 08:45 UTC, glukosseth commented
@hikaruNagamine  ok, thanks for your comment, do I need to do something to correct PR?

2022-07-02 09:32 UTC, hikaruNagamine commented
@glukosseth 
Please see the comments at this link for the correction.
https://github.com/UnUniFi/gitbook/pull/14#discussion_r911114052
https://github.com/UnUniFi/gitbook/pull/14#discussion_r911121257

2022-07-03 04:04 UTC, hikaruNagamine requested changes
@glukosseth 
There is one more point that we would like you to correct, please review the comments.

2022-07-03 04:04 UTC, hikaruNagamine commented on validators/ununifid-installation-and-setup.md
> +go version go1.18.2 linux/amd64
```suggestion
# Please install Go v1.17
# from $HOME dir
$ wget https://go.dev/dl/go1.17.linux-amd64.tar.gz
$ sudo rm -rf /usr/local/go
$ sudo tar -C /usr/local -xzf go1.17.linux-amd64.tar.gz
$ go version
go version go1.17 linux/amd64
```
I would like the go version to match the 1.17 indicated in the README of the [chain repository](https://github.com/UnUniFi/chain#install).
So please make this correction.

2022-07-04 16:29 UTC, glukosseth commented
ok, done

2022-07-06 13:14 UTC, hikaruNagamine approved these changes
LGTM

2022-07-06 13:20 UTC, hikaruNagamine commented
@taiki1frsy 
I have approved the review.
Please confirm your approval.

Please check here as well.
https://github.com/UnUniFi/gitbook/pull/15
https://github.com/UnUniFi/gitbook/pull/16

2022-07-07 05:25 UTC, taiki1frsy approved these changes

2022-07-07 05:30 UTC, merged